### ISSUE TITLE
How to run pretrained model on LM-O

### ISSUE THREAD

**Issue by nmerrillq** [suyz526/ZebraPose#42]
Hello,

I am trying to reproduce your results on LM-O, but I am running into some trouble. I downloaded the pretrained model from [here](https://cloud.dfki.de/owncloud/index.php/s/EmQDWgd5ipbdw3E?path=%2Fpaper%2Flmo). I ran the command `python test.py --cfg config/config_BOP/lmo/exp_lmo_BOP.txt --obj_name ape --ckpt_file checkpoints/pretrained_lmo_paper/ape --ignore_bit 0 --eval_output_path results/lmo/pretrained_paper/ape` like in the README but I got 

```
Traceback (most recent call last):
  File "/home/nate/git/ZebraPose/zebrapose/test.py", line 425, in <module>
    main(configs)
  File "/home/nate/git/ZebraPose/zebrapose/test.py", line 176, in main
    if configs['detector']=='FCOS':
KeyError: 'detector'
```

Then I tried another config:
```
python test.py --cfg config/config_BOP_effnet/lmo/lmo_BOP_effnet_test.txt --obj_name ape --ckpt_file checkpoints/pretrained_lmo_paper/ape --ignore_bit 0 --eval_output_path results/lmo/pretrained_paper/ape
```
and got 
```
Traceback (most recent call last):
  File "/home/nate/git/ZebraPose/zebrapose/test.py", line 425, in <module>
    main(configs)
  File "/home/nate/git/ZebraPose/zebrapose/test.py", line 212, in main
    net.load_state_dict(checkpoint['model_state_dict'])
  File "/home/nate/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for BinaryCodeNet_Deeplab:
	Missing key(s) in state_dict:...
```
followed by a long list of missing keys. Could you please provide the correct command?

**Comment by athnzc** [comment]
Hello, I am not one of the authors, but perhaps your error has to do with incompatibility between the provided pytorch pretrained model and the version of Pytorch that you are using. Maybe you could try installing Python 3.6 and pytorch 1.10 and see if the model is loaded in that case.
